using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebClient.Model
{
    public partial class Guest
    {
        public int Guest_No { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }

        public Guest()
        {
            
        }

        public Guest(int guestNo, string name, string address)
        {
            Guest_No = guestNo;
            Name = name;
            Address = address;
        }

        public override string ToString()
        {
            return $"Guest_No: {Guest_No}, Name: {Name}, Address: {Address}";
        }

        #region Autogenerated Code
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public Guest()
        //{
        //    //Bookings = new HashSet<Booking>();
        //}

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<Booking> Bookings { get; set; }
    } 
    #endregion
}
